// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/aarondever/notiflow/internal/config"
	"github.com/aarondever/notiflow/internal/database"
	"github.com/aarondever/notiflow/internal/handlers"
	"github.com/aarondever/notiflow/internal/services"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitializeApp uses Wire to initialize all dependencies
func InitializeApp(cfg *config.Config) (*App, error) {
	databaseDatabase, err := database.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	emailService := services.NewEmailService(databaseDatabase, cfg)
	emailHandler := handlers.NewEmailHandler(emailService)
	app := NewApp(databaseDatabase, emailHandler)
	return app, nil
}

// wire.go:

type App struct {
	DB     *database.Database
	Router *gin.Engine
}

func NewApp(
	db *database.Database,
	emailHandler *handlers.EmailHandler,

) *App {
	router := gin.Default()

	emailHandler.SetupRouters(router)

	return &App{
		DB:     db,
		Router: router,
	}
}
